name: members_space_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/logo/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
